services:
  grafana:
    image: grafana/grafana:11.5.0
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    command:
      - cfg:default.log.level=warn
    volumes:
      - ./volumes/grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # TODO: https://github.com/prometheus/common/issues/522
      - --log.level=warn
    volumes:
      - ./prometheus:/etc/prometheus
      - ./volumes/prometheus:/prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    restart: unless-stopped
    command:
      - --path.rootfs=/host
      # TODO: https://github.com/prometheus/common/issues/522
      - --log.level=warn
    volumes:
      - /:/host:ro,rslave
