services:
  grafana:
    image: grafana/grafana:12.3.2
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    command:
      - cfg:default.log.level=warn
    volumes:
      - ./volumes/grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.8.1
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # TODO: https://github.com/prometheus/common/issues/522
      - --log.level=warn
    ports:
      - 127.0.0.1:3001:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./volumes/prometheus:/prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    restart: unless-stopped
    command:
      - --path.rootfs=/host
      # TODO: https://github.com/prometheus/common/issues/522
      - --log.level=warn
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    privileged: true
    command:
      # TODO:
      # https://github.com/google/cadvisor/issues/3357
      # https://github.com/google/cadvisor/issues/3139
      - --disable_metrics=disk,referenced_memory
      - -v=0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
