# TODO: Configure persistence
services:
  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v3.0.1
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus
      - ./volumes/prometheus:/prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
